### ISSUE TITLE
License violation

### ISSUE THREAD

**Issue by bostrom** [Pnlvfx/text-to-image-2#1]
Hi @Pnlvfx and thanks for keeping this code alive. 

I'm very happy to see you continuing my work. However, since this is based on a copy of my [original work](https://github.com/bostrom/text-to-image), which uses the ICS license, you're not actually permitted to [replace my original copyright notice](https://github.com/Pnlvfx/text-to-image-2/blob/5daa8d6b91f871c74d34ba879259e45cfdd9af55/LICENSE#L3) in the LICENSE file. 

According to the [ICS license](https://opensource.org/license/isc-license-txt):

> Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby granted, **provided that the above copyright notice and this permission notice appear in all copies**.

Please instead add your own name below mine and keep up the good work! 

Thanks,
Fred

**Comment by Pnlvfx** [comment]
Hi Fred,

Thank you so much for pointing that out, and I sincerely apologize for the mistake. I didn’t fully understand how the ISC license works, but I’ve now corrected it and restored your original copyright notice in the LICENSE file. I’ve also added my name below yours, as you suggested.

I really appreciate your understanding, and I’ll be more careful with these details moving forward.

Thanks again for your patience and support!
